### PR TITLE
Update to latest template.

### PR DESCRIPTION
**Pull request by fdamken**
I've updated the meta-files to the latest version provided in the [sample plugin](https://github.com/obsidianmd/obsidian-sample-plugin), making the plugin work with Obsidian ^1.0.0.

### CODE REVIEW

**Comment by Peer202** [comment]
@fdamken  sadly your fork doesnt compile on my end. I assume there  is something wrong with my develeopment setup, because i dont know much about typescript but this doesnt look like a valid error. Could you submit your version to the Obsidian Community Plugin list so its easy to use? Or @SsSanzo  could you merge this Pull Request and bring the plugin into the community Plugin Repo? 

> src/render.ts:55:39 - error TS2454: Variable 'milestoneStartDate' is used before being assigned.
> 
> 55             this.startDate = new Date(milestoneStartDate);
>                                          ~~~~~~~~~~~~~~~~~~
> 
> src/render.ts:56:37 - error TS2454: Variable 'milestoneEndDate' is used before being assigned.
> 
> 56             this.endDate = new Date(milestoneEndDate);
>                                        ~~~~~~~~~~~~~~~~
> 
> src/render.ts:58:39 - error TS2454: Variable 'taskStartDate' is used before being assigned.
> 
> 58             this.startDate = new Date(taskStartDate);
>                                          ~~~~~~~~~~~~~
> 
> src/render.ts:59:37 - error TS2454: Variable 'taskEndDate' is used before being assigned.
> 
> 59             this.endDate = new Date(taskEndDate);
>                                        ~~~~~~~~~~~
> 
> src/render.ts:63:16 - error TS2454: Variable 'milestoneStartDate' is used before being assigned.
> 
> 63             if(milestoneStartDate<taskStartDate)
>                   ~~~~~~~~~~~~~~~~~~
> 
> src/render.ts:63:35 - error TS2454: Variable 'taskStartDate' is used before being assigned.
> 
> 63             if(milestoneStartDate<taskStartDate)
>                                      ~~~~~~~~~~~~~
> 
> src/render.ts:64:43 - error TS2454: Variable 'milestoneStartDate' is used before being assigned.
> 
> 64                 this.startDate = new Date(milestoneStartDate);
>                                              ~~~~~~~~~~~~~~~~~~
> 
> src/render.ts:66:43 - error TS2454: Variable 'taskStartDate' is used before being assigned.
> 
> 66                 this.startDate = new Date(taskStartDate);
>                                              ~~~~~~~~~~~~~
> 
> src/render.ts:68:16 - error TS2454: Variable 'milestoneEndDate' is used before being assigned.
> 
> 68             if(milestoneEndDate>taskEndDate)
>                   ~~~~~~~~~~~~~~~~
> 
> src/render.ts:68:33 - error TS2454: Variable 'taskEndDate' is used before being assigned.
> 
> 68             if(milestoneEndDate>taskEndDate)
>                                    ~~~~~~~~~~~
> 
> src/render.ts:69:41 - error TS2454: Variable 'milestoneEndDate' is used before being assigned.
> 
> 69                 this.endDate = new Date(milestoneEndDate);
>                                            ~~~~~~~~~~~~~~~~
> 
> src/render.ts:71:41 - error TS2454: Variable 'taskEndDate' is used before being assigned.
> 
> 71                 this.endDate = new Date(taskEndDate);
>                                            ~~~~~~~~~~~
> 
> src/render.ts:99:9 - error TS2322: Type 'SVGSVGElement | null' is not assignable to type 'Node'.
>   Type 'null' is not assignable to type 'Node'.
> 
> 99         return svg.node();
>            ~~~~~~~~~~~~~~~~~~
